# NUMPY

In [1]:
#Numpy stands for numerical data also known as numerical python
#ARRAY:Continues allocation of memory
#numpy.array([.......])
#works only with number data
#it is a library consisiting of multi dimensional arrays

In [2]:
import numpy

In [3]:
#creating a simle array
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
#array can also be assigned to a variable
b= numpy.array([11,121,3,4])

In [5]:
b

array([ 11, 121,   3,   4])

In [6]:
#this can also be used by having a alias name
import numpy as np
b=np.array([1,2,3,45,6])
b

array([ 1,  2,  3, 45,  6])

In [7]:
#there are certain attributes in numpy
b.shape

(5,)

In [19]:
#2 dimensional object
#2*2 matrix
c=np.array([[1,2],[3,4]])
print(c)
c.shape

[[1 2]
 [3 4]]


(2, 2)

In [20]:
#3*2 matrix
c=np.array([[1,2],[2,3],[3,4]])
print(c)
c.shape

[[1 2]
 [2 3]
 [3 4]]


(3, 2)

In [21]:
#3*3 matrix
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
c.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [23]:
#3*4 matrix
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)
c.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [24]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(c)
c.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [25]:
c=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(c)
c.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


(5, 3)

In [26]:
c=np.array([[1,2],[4,5],[7,8],[10,11]])
print(c)
c.shape

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]


(4, 2)

In [28]:
c=np.array([[1,2,10,11],[4,5,7,8]])
print(c)
c.shape

[[ 1  2 10 11]
 [ 4  5  7  8]]


(2, 4)

In [29]:
c=np.array([[1,2,3,11,12],[4,5,6,14,15],[7,8,9,34,56]])
print(c)
c.shape

[[ 1  2  3 11 12]
 [ 4  5  6 14 15]
 [ 7  8  9 34 56]]


(3, 5)

In [30]:
a=c.reshape(5,3)
print(a)
a.shape

[[ 1  2  3]
 [11 12  4]
 [ 5  6 14]
 [15  7  8]
 [ 9 34 56]]


(5, 3)

In [39]:
#gives the min value of the elemnt in array
a.min()

1

In [40]:
#gives the max value of the elemnt in array
a.max()

56

In [41]:
#give the mean value
a.mean()

12.466666666666667

In [42]:
#gives the count of the elemnts in array
a.size

15

In [45]:
#gives the number of bytes/memory occupied by each element
a.itemsize

4

In [46]:
#give sthe memory address
a.data

In [48]:
#to check the data type
a.dtype

dtype('int32')

In [63]:
#to change the dtype
a=np.array([[1,2],[3,4]],dtype='float64')
a

array([[1., 2.],
       [3., 4.]])

In [64]:
a.dtype

dtype('float64')

In [65]:
#this will be gives as 8 as float takes as 64 ====>64/8 ==>float takes 8 bytes to store the data
#default wil be taken as int 32
a.itemsize

8

In [66]:
a.shape

(2, 2)

In [67]:
a=np.array([[1,2],[3,4],[5,6]],dtype='float64')
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [68]:
a.shape

(3, 2)

In [69]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [70]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [71]:
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
#we can reshape the one-dimensional to multi dimensional on on econdition that size should satisfy
c=b.reshape(5,3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [74]:
#if the value count is more it takes int 64 that means 8 bytes for element
a=np.array([[11111111111111111111111111111111111111111111111111111111111111111,222222222222222222222222222222222222222222222222],[33333333333333333333333333333333333333333333333333333333333333,44444444444444444444444444444444444444444444444444444444]])
a


array([[11111111111111111111111111111111111111111111111111111111111111111,
        222222222222222222222222222222222222222222222222],
       [33333333333333333333333333333333333333333333333333333333333333,
        44444444444444444444444444444444444444444444444444444444]],
      dtype=object)

In [75]:
a.shape

(2, 2)

In [76]:
a.itemsize

8

In [81]:
b=np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
a=b.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
#both reshape and arange can be done in single line
b=np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
b.shape

(5, 5)

In [86]:
#number of dimensions i.e coordinates
a.ndim

2

In [87]:
#as the array is nd array when we search for type it gives as nd array
type(a)

numpy.ndarray

In [88]:
b=np.array([[1.5,2,3],[5,6,7]],dtype='float32')
b

array([[1.5, 2. , 3. ],
       [5. , 6. , 7. ]], dtype=float32)

In [89]:
a=np.array([[1.5,2,3],[5,6,7]],dtype='int32')
a

array([[1, 2, 3],
       [5, 6, 7]])

In [90]:
b.itemsize

4

In [92]:
a=np.array([[1,2,3],[65,34,65],[100,101,102]])
a

array([[  1,   2,   3],
       [ 65,  34,  65],
       [100, 101, 102]])

In [93]:
#we have a function call ravel which converts multi dimensonal to one-d vector
print(a.ravel())

[  1   2   3  65  34  65 100 101 102]


In [96]:
#internal method of numpy which give all zeros for gives matrix size
c=np.zeros((5,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
#internal method of numpy which give all ones for gives matrix size
c=np.ones([5,5])
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [101]:
#arange function ca also take strat end and skip are used
#normal arange
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [102]:
#arange with start point
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [103]:
#arange with start,end and skip
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [104]:
a=np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [105]:
print(a.ravel())

[10 15 20 25]


# Broadcasting in numpy

In [106]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [107]:
a=np.array([1,2,3])
b=np.array([4])
a*b

array([ 4,  8, 12])

In [108]:
a=np.array([10,20,30,40])
b=np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [109]:
a-b

array([10, 19, 28, 37])

In [110]:
b

array([0, 1, 2, 3])

In [111]:
b**2

array([0, 1, 4, 9], dtype=int32)

# Random library with numpy

In [112]:
#random method generates a random numbers between 0-1
b=np.random.random([2,3])
b

array([[0.17431212, 0.96240475, 0.94599489],
       [0.95983817, 0.70909472, 0.85164483]])

In [129]:
#we have other function rand which behaves same as random
b=np.random.rand(2,3)
b

array([[0.38499796, 0.68065578, 0.31249244],
       [0.52696469, 0.12979817, 0.7990689 ]])

In [130]:
#we have other function called randn this gives negative and positive values
c=np.random.randn(2,3)
c

array([[ 0.7755329 , -0.17153358,  1.89500982],
       [ 1.17362997, -0.28957116,  0.05670785]])

# Universal functions

In [113]:
b=np.arange(3)

In [114]:
b

array([0, 1, 2])

In [115]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [116]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [117]:
b=np.arange(3)

In [118]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [119]:
b

array([0, 1, 2])

In [122]:
c=np.array([4,5,6])
d=np.add(b,c)
d

array([4, 6, 8])

# indexing slicing and iterating

In [123]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
a[2]

2

In [125]:
a[2:5]

array([2, 3, 4])

In [126]:
a[-1]

9

# representin missing data

In [127]:
a=np.array([np.nan,2,3,5,6,np.nan,np.nan])
a

array([nan,  2.,  3.,  5.,  6., nan, nan])